# Generated by Django 2.2.10 on 2020-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hris_id',
            field=models.CharField(max_length=5, verbose_name='HRIS ID'),
        ),
    ]
