# Generated by Django 2.2.10 on 2020-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('employeeCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(blank=True, max_length=255, null=True)),
                ('emailAddress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
