# Generated by Django 2.2.10 on 2020-03-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_emailaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaddress',
            old_name='emailAddress',
            new_name='EmailAddress',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='employeeCode',
            new_name='EmployeeCode',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='employeeName',
            new_name='EmployeeName',
        ),
    ]
