# Generated by Django 2.2.10 on 2020-03-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200305_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaddress',
            old_name='EmailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='EmployeeCode',
            new_name='employee_code',
        ),
        migrations.RenameField(
            model_name='emailaddress',
            old_name='EmployeeName',
            new_name='employee_name',
        ),
    ]
